# A brief introduction about me

Hi Readers, I’m **Idris Baba.**

Welcome to my **learning diary**, where I share insights and discoveries from the "Remotely Sensing Cities and Environments" module, which is part of the Master of Urban Spatial Science program at center for advanced spatial analysis (CASA) at University College London, delivered by Andy Maclachlan. This journey began with my realization of the growing need of programming skills in geographical data science. To bridge this gap, I decided to embark on this master's program, aiming to blend my GIS expertise with advanced programming skills to meet the demands of the evolving geospatial industry.

This module is particularly relevant to my professional career, given my background in geography from my undergraduate studies. My career has largely revolved around remotely sensed data. I started as a junior GIS specialist at a state government office, focusing on cadastral mapping. Soon after that, I took on a voluntary humanitarian role as a GIS technician, creating maps for various humanitarian purposes. My career took a significant leap when I joined the multinational highway feasibility project for the Abidjan-Lagos Corridor within West African sub-region, covering five major West African countries.

I personnally find every bit of the topics introduced in this module to be really interesting and highly relevant to my past experiences. The principles of earth observation are not only applicable to my professional work but also to the non-governmental organization I co-founded. Our main aim is to tackle the evolving issues of climate change, and I believe these principles I'm learning can be instrumental in providing early warning signs and solutions.

Moreover, I realized that this course could address many of the data accessibility issues we encounter during the preliminary stage of feasibility studies in construction projects. It has the capability of enhancing the accuracy of most of the analyses we conduct, and this can also reduce the time required to produce high-quality reports. Considering the challenges of data accessibility in Nigeria, a third-world country, remote sensing approaches offer promising solutions.

