## Portfolio

## Summary

This week felt like a tutorial-focused experience, with the main emphasis on learning to use Xaringan and Quarto, for creating this learning diary and preparing a group presentation, which I completely understood why andy introduced us to this amazing tool. So basically, the lectures highlighted on different functionality and usability of the tools, which i come to realize how these tools serve as powerful resources for data science projects and presentations. I was introduced to various styling and formatting options for Xaringan slides and Quarto book.

I plan to use these tools collaboratively in R to contribute to the group presentation we were given which is part of our assesement for this course, as well as create a personal Xaringan slide exploring the characteristics of Landsat and Sentinel imagery. Essentially, these tools will be applied in all of my outputs from this course , including the group presentation, my personal presentation, and a Quarto book, which will ultimately be hosted on GitHub

#### **Limitations**

While I believe this is a powerful tool, the requirement for specialized skills can make it a bit daunting. Using these tools demands a level of motivation and effort, especially when compared to more straightforward presentation software that doesn't require technical expertise or special programs to operate

## Xaringan Presentation

<iframe src="https://idrisbaba.github.io/xaringan-presentation/#1" width="100%" height="600px" frameborder="0" allowfullscreen>

</iframe>

## Reflection:

I find the use of Xaringan a bit difficult because this is my first time learning about presentation tool called **Xaringan**, so I found myself struggling to make the presentation, So I was mostly going on YouTube to see the **"how to"** but at last I was able to figured out how to do the xaringan presentation, it seems easier afterwards even though there are some features that i'm yet to explore, and I really think this could be used as a powerful tool to convey your message in a structured format, while including different interactive contents such as videos and pictures which will support your presentation and make it seamless, I also think this tool will be beneficial to programmers which is alot better than power-point as it give you a section for chunk of codes and also gives you other formatting experience like annotations, and a powerful customization, overall I am looking forward to exploring this powerful tool more.

Another thing is, I feel like my skill on the use of github has improved, for the fact that everytime I render I will push to github. so engaging in the same process over and over made me improved on my github skills.

Here are some of the **resources** I found useful

## Useful Resources

Here are some helpful references that I found valuable while working on this portfolio:

\[Quick Start Guide for Quarto Books\](<https://quarto.org/docs/books/#quick-start>)

\[xaringan Presentation Framework\](<https://bookdown.org/yihui/rmarkdown/xaringan.html>)

\[Xaringan CSS Theme Generator Framework\](<https://cran.r-project.org/web/packages/xaringanthemer/vignettes/xaringanthemer.html>)
