## Temperature and Policy:

## Summary:

Some of the discussions and topics covered this week, were Implementation of different temperature policies around the world, that were impacted by issues of climate change or trying to improve the liveability of the city these is in conformity with Sustainable Development Goals (SDG) which were targets with measurable indicators for monitoring, such as making cities and human settlements inclusive, safe, resilient and sustainable which is under goal number 11 we also covered topics like Urban Heat Ireland, factors responsible for urban heat Ireland, social and environmental implications of urban Heat Ireland and how societies are making an attempt to adjust and make amends, while Investing in parks and green spaces. some of the city policies covered are: Medellín Green Corridors, Superblock in Barcelona, Fremantle's Urban Forest Plan, Global policy documents, Metropolitan (city) policy, Perth and Peel \@3.5 million, The London Plan, Singapore’s Master Plan, Seattle’s Green Factor and Baton Rouge’s landscape ordinance.

**Independent thought:**

I find the Barcelona superblocks to be quite interesting, how i wish cities were as flexible as Barcelona in fast implementation of policy, these could have taken us a lot further in achieving goal 11 of the US sustainable development goal. For the fact that Barcelona was struggling with a lot of environmental and social problem, and they were able to take the bold step towards making their city cleaner and better.   

**limitations:**

Based on what i have been observing around the world, I realized that one among many limitation of these policies is that they're very hard to achieve and there might aslo be some political draw backs or challenges in regards to its implementation, most political institutions as not as swift as in the case of Barcelona. cities out to act fast to see results.

**Comment:**

## Application:

## Reflection

This week I was able to improve on my policy application knowledge while realizing most countries are developing their own personal policies towards the betterment of their people, even though there is a global policy the is a local policy that is targeted to country's needs.  

I believe my knowledge will be reflected in the sense that using our non-governmental organization and coming from a low and middle income country  its very important to see how we can implement these policies because these problem is global, continuous negligence or rather human activity keep putting the world at risk of UHI, Flooding, and bush fires. While from my own local context UHI and desertification.
