on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install additional R dependencies
        run: |
          Rscript -e 'install.packages(c("bookdown"))'

      - name: Install R Dependencies (renv)
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Quarto Project
        run: |
          quarto render ./  # Render the project to generate the output files

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: docs  # Ensure this matches your Quarto output directory
          path: ./      # Ensure this points to the root of your Quarto project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Output Files
        run: |
          echo "Listing generated files in the 'docs' directory:"
          ls -la docs